// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/clear-cache.ts";
import * as $3 from "./routes/deno-kv/index.tsx";
import * as $4 from "./routes/greet/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/page2.tsx";
import * as $7 from "./routes/streaming.tsx";
import * as $8 from "./routes/streaming/simple.tsx";
import * as $$0 from "./islands/aniflix-episode-tanstack.tsx";
import * as $$1 from "./islands/clear-cache-button.tsx";
import * as $$2 from "./islands/sse-debug.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/clear-cache.ts": $2,
    "./routes/deno-kv/index.tsx": $3,
    "./routes/greet/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/page2.tsx": $6,
    "./routes/streaming.tsx": $7,
    "./routes/streaming/simple.tsx": $8,
  },
  islands: {
    "./islands/aniflix-episode-tanstack.tsx": $$0,
    "./islands/clear-cache-button.tsx": $$1,
    "./islands/sse-debug.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
